<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
iris flowers
</font>
</h1>

# summary
in this simple projects we want to see impact of using linear algebra in reducing <code>for</code> loops and it's effect in speed of KNN algorithm as example

we will use <code>iris flowers</code> dataset and <code>numpy</code> library for our work

In [2]:
import numpy as np
# include iris features
irises = np.load('data/irises.npy')
# include iris types
types = np.load('data/types.npy')
# include new iris features
new_irises = np.load('data/new_irises.npy')


print(irises.shape)
print(types.shape)
print(new_irises.shape)
n, m = len(irises), len(new_irises)  # n for iris count , m for new iris count

(120, 4)
(120,)
(30, 4)


# with Two loop
in first step we use easiest way, and use 2 loop for work

In [3]:
def calc_two_loops(new_points, points):
    m, n = len(new_points), len(points)
    d = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            d[i, j] = np.sum(np.square( new_points[i]-points[j]))
    return d

# with One loop
in second step we go further , and use 1 loop for work

In [9]:
def calc_one_loop(new_points, points):
    m, n = len(new_points), len(points)    
    d = np.zeros((m, n))
    for i in range(m):
        d[i] = np.sum(np.square(points - new_points[i]),axis=1)
    return d

# with no loop
in last step we want to do it without loop:

we can reshape our data and convert it to 3d array to calculate distance in each layer without loop.
<p style="text-align:center;"><img src="fig.png"></p>

In [7]:
def calc_no_loop(new_points, points):
    return np.sum( np.square(points- new_points.reshape(30 , 1,4)),axis=2)

at the end:
* we should check the result of 3 method and they should be same.
* compare speed of each 3 method

In [10]:
d2 = calc_two_loops(new_irises, irises)
d1 = calc_one_loop(new_irises, irises)
d = calc_no_loop(new_irises, irises)

if np.allclose(d, d1, 1e-5) and np.allclose(d, d2, 1e-5):
    print('Fine!')
else:
    print('There is something wrong!')

Fine!


as you see they are same,
now we go further

because next steps of KNN is same, at this step we can compare our speed

In [29]:
%%timeit
calc_two_loops(new_irises , irises);

25.9 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
%%timeit
calc_one_loop(new_irises , irises);

419 µs ± 51.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [33]:
%%timeit
calc_no_loop(new_irises , irises);

111 µs ± 2.24 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


<code>calc_no_loop</code> is much much faster :)

we achieve our main goal (compare speed).

but we can continue and complete our KNN algo

after calculate distance we must sort and choose <code>N</code> nearest neighbors. bacause we just want first <code>N</code> , we can use <code>argpartition</code> to return <code>N</code> near.

In [34]:
k = 10
k_nearest = np.argpartition(d , 10,axis=1)[: , :10]
k_nearest

array([[  6,  14,   0,  32,  22,  17,  39,  21,  23,  37],
       [ 10,   1,  30,  24,  20,   2,  36,   3,   6,  28],
       [ 27,  13,   8,  39,   4,  29,  15,  12,  26,  25],
       [ 14,  17,   0,  39,  37,  22,   8,  32,  26,  13],
       [ 21,  20,  30,   3,   9,  24,   6,  19,  35,   5],
       [ 10,   1,   2,   3,  38,   5,  36,  30,  24,   9],
       [ 10,   1,  30,  24,  20,   2,  36,   3,   6,  28],
       [  0,   6,  22,  23,  21,  14,   9,  32,  17,  39],
       [ 39,  35,  17,  22,   4,  21,  37,  19,   8,  16],
       [ 28,   6,  23,   0,  14,  21,  30,  32,  22,   9],
       [ 47,  73,  69,  61,  52,  51,  41,  60, 101,  58],
       [ 71,  43,  65,  64,  77,  72,  66,  76,  74,  54],
       [ 71,  65,  74,  64,  66,  77,  76,  54,  57,  49],
       [ 64,  65,  74,  66,  43,  50,  54,  72,  77,  71],
       [ 78,  60,  47,  41,  73,  52,  63,  57,  51,  59],
       [ 74,  65,  54,  64,  66,  43,  50,  57,  71,  75],
       [ 77,  71,  44,  53,  72,  76,  49,  97,  56,  63

now we can use their arg to find type of them

In [35]:
k_nearest_types = types[k_nearest]
k_nearest_types

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 2, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
       [2, 1, 2, 2, 1, 2, 2, 2, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2,

at the end we get <code>mode</code> of each list

In [36]:
from scipy import stats
predicted_types = stats.mode(k_nearest_types, axis=1).mode.reshape(m)
predicted_types

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

now we can compare our prediction with <code>new_types.npy</code>.

In [37]:
new_types = np.load('data/new_types.npy')
accuracy = np.sum(np.equal(new_types,predicted_types)) / np.size(new_types)
print('Accuracy:', accuracy)

Accuracy: 1.0
